- name: Create MariaDb Container
  docker_container:
    name: mariadb
    image: mariadb
    state: started
    restart: yes
    ports:
      - 3306:3306
    env:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: ansible