# commande d'execussion  ansible-playbook apache-deploy/playbook.yml -i targets.txt 
-
  name: Apache deploy
  hosts: all
  become: yes 

  vars:
    users: ['porthos','athos','aramis']
    group: Musketeers

  tasks:
    - name: Apt apache + PHP
      apt: name={{item}} state=latest
      loop: ['apache2','php','libapache2-mod-php','php-mysql']

    - name: Start Apach
      service: name=apache2 state=started #state=reloaded

    - name: Create group Musketeers
      group: name={{group}} state=present

    - name: Create user
      user: name={{item}} state=present group={{group}}
      loop: "{{ users }}"
    
    - name: Create user folder in Apache Document Root
      file: path=/var/www/html/{{item}} state=directory
      loop: "{{users}}"

    - name: Copy php files
      copy: src=files/index.php dest=/var/www/html/{{item}} owner={{item}}
      loop: "{{users}}"



- 
  name: Create MariaDb Container
  tags: mariadb
  hosts: all
  become: yes
  roles:
    - docker
    - container

